### ISSUE TITLE
HOL step by step

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#12]
looks like this is still a work in process.  Lots of Insert here comments??  Not sure if this is meant to be this way to customize this workshop?

**Comment by joelhulen** [comment]
Yes, this is a draft. Those "insert here" comments are part of the standard MCW template. I will replace those comments after the review is completed just in case any of the information that goes into those places need to change.

**Comment by joelhulen** [comment]
Closing, as this is addressed by latest changes.
