### ISSUE TITLE
notebook 2 - read data from HDFS command

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#13]
This command is failing with following error:
Msg 105100, Level 16, State 1, Line 1
105100;HDFS Query failed with error 'The remote server returned an error: (404) Not Found.'.
OLE DB provider "SQLNCLI11" for linked server "(null)" returned message "Unspecified error".
 Msg 7421, Level 16, State 2, Line 3
Cannot fetch the rowset from OLE DB provider "SQLNCLI11" for linked server "(null)". .

**Comment by joelhulen** [comment]
Did you re-run the file upload command with the fixed path? (**upload-sample-files.cmd**)

**Comment by lifox1** [comment]
No but I will try that

Lisa Fox | TSP-Data Platform| Financial Services East
C: 734-883-1408
Lisa.fox@microsoft.com

[cid:image003.jpg@01CE4293.4A0EC230]

**Comment by lifox1** [comment]
> Did you re-run the file upload command with the fixed path? (upload-sample-files.cmd)

I do not see an updated one out there?

**Comment by lifox1** [comment]
This is resolved now with the fixed path and rerunning the upload-sample-files.cmd
