### ISSUE TITLE
notebook 3 failure

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#14]
no data getting into the web_clickstreams_hdfs table so it fails on the insert into - cell 4 with this error:

Msg 7320, Level 16, State 102, Line 2
Cannot execute the query "Remote Query" against OLE DB provider "SQLNCLI11" for linked server "SQLNCLI11". 105100;HDFS Query failed with error 'The remote server returned an error: (404) Not Found.'.

**Comment by joelhulen** [comment]
Do you see a subfolder underneath HDFS in Azure Data Studio called **web_logs**? If so, does it have a file underneath named **web_clickstreams.csv**?

![image](https://user-images.githubusercontent.com/5950304/60213599-d7a14280-9831-11e9-8ae4-7dfc525a43c1.png)

**Comment by lifox1** [comment]
no that folder does not exist

**Comment by joelhulen** [comment]
That should've been added when you re-ran the `upload-sample-files` command. Can you try running it again please?

**Comment by lifox1** [comment]
here is the output:
C:\Users\lifox>.\upload-sample-files.cmd 104.42.55.227 MySQLBigData2019
Verifying curl.exe is in path
The syntax of the command is incorrect.
C:\Users\lifox\AppData\Local\Temp
Creating HDFS directories to store file data...
HTTP/1.1 200 OK
Date: Wed, 26 Jun 2019 20:59:24 GMT
Set-Cookie: JSESSIONID=1oieiqf2hduaugd71i41qd77j;Path=/gateway/default;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/default; Max-Age=0; Expires=Tue, 25-Jun-2019 20:59:24 GMT
Cache-Control: no-cache
Expires: Wed, 26 Jun 2019 20:59:24 GMT
Date: Wed, 26 Jun 2019 20:59:24 GMT
Pragma: no-cache
Expires: Wed, 26 Jun 2019 20:59:24 GMT
Date: Wed, 26 Jun 2019 20:59:24 GMT
Pragma: no-cache
Content-Type: application/json; charset=UTF-8
X-FRAME-OPTIONS: SAMEORIGIN
Content-Length: 16
Server: Jetty(9.2.22.v20170606)

{"boolean":true}HTTP/1.1 200 OK
Date: Wed, 26 Jun 2019 20:59:25 GMT
Set-Cookie: JSESSIONID=161fhcu41keinekhvzck0wd2p;Path=/gateway/default;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/default; Max-Age=0; Expires=Tue, 25-Jun-2019 20:59:25 GMT
Cache-Control: no-cache
Expires: Wed, 26 Jun 2019 20:59:25 GMT
Date: Wed, 26 Jun 2019 20:59:25 GMT
Pragma: no-cache
Expires: Wed, 26 Jun 2019 20:59:25 GMT
Date: Wed, 26 Jun 2019 20:59:25 GMT
Pragma: no-cache
Content-Type: application/json; charset=UTF-8
X-FRAME-OPTIONS: SAMEORIGIN
Content-Length: 16
Server: Jetty(9.2.22.v20170606)

{"boolean":true}Downloading source files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43717  100 43717    0     0  43717      0  0:00:01 --:--:--  0:00:01 71784
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14403  100 14403    0     0  14403      0  0:00:01 --:--:--  0:00:01 31794
Uploading data files to HDFS...
HTTP/1.1 307 Temporary Redirect
Date: Wed, 26 Jun 2019 20:59:27 GMT
Set-Cookie: JSESSIONID=1xjptcxrzsee5mwch15nd4x0e;Path=/gateway/default;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/default; Max-Age=0; Expires=Tue, 25-Jun-2019 20:59:27 GMT
Cache-Control: no-cache
Expires: Wed, 26 Jun 2019 20:59:27 GMT
Date: Wed, 26 Jun 2019 20:59:27 GMT
Pragma: no-cache
Expires: Wed, 26 Jun 2019 20:59:27 GMT
Date: Wed, 26 Jun 2019 20:59:27 GMT
Pragma: no-cache
Content-Type: application/octet-stream
X-FRAME-OPTIONS: SAMEORIGIN
Location: https://104.42.55.227:30443/gateway/default/webhdfs/data/v1/webhdfs/v1/partner_customers/customers.csv?_=AAAACAAAABAAAADQmPvy6H6_Co71R0DZ0VmSb6StnYzxk15_kuv5HFf3817nV9yMikGMcPrNp6iH4gGG6nEH52KNFh2QZtvpWGrhlsJi4_LTeo9VqfIzk0cDdDOWK8_1l0fNRUpdvaor5HV681MnWaT_CLhBIhxY57i-uSTae6mf96AC6Oep3OAd-q_Rx4soQCnZDQ55wAzoLq04iPb05-MIkRT3TxjznL3er7XGDqG16n--LMROLIsunUk-bsWCsr-rHv0Y5Fno7p-6s_KhO_U1qSvf94A29GLVSlZ8n-c6X_bwOtzCx_RU0FBoxP0acwSmsA
Content-Length: 0
Connection: close
Server: Jetty(9.2.22.v20170606)

HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Date: Wed, 26 Jun 2019 20:59:27 GMT
Set-Cookie: JSESSIONID=1b5zaoarml6txr67u9kymm64f;Path=/gateway/default;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/default; Max-Age=0; Expires=Tue, 25-Jun-2019 20:59:27 GMT
Location: https://104.42.55.227:30443/gateway/default/webhdfs/v1/partner_customers/customers.csv
Access-Control-Allow-Origin: *
Connection: close
Server: Jetty(9.2.22.v20170606)

HTTP/1.1 307 Temporary Redirect
Date: Wed, 26 Jun 2019 20:59:29 GMT
Set-Cookie: JSESSIONID=ahv00dsnwfya10gviki59vnwp;Path=/gateway/default;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/default; Max-Age=0; Expires=Tue, 25-Jun-2019 20:59:29 GMT
Cache-Control: no-cache
Expires: Wed, 26 Jun 2019 20:59:29 GMT
Date: Wed, 26 Jun 2019 20:59:29 GMT
Pragma: no-cache
Expires: Wed, 26 Jun 2019 20:59:29 GMT
Date: Wed, 26 Jun 2019 20:59:29 GMT
Pragma: no-cache
Content-Type: application/octet-stream
X-FRAME-OPTIONS: SAMEORIGIN
Location: https://104.42.55.227:30443/gateway/default/webhdfs/data/v1/webhdfs/v1/partner_products/products.csv?_=AAAACAAAABAAAADQiYs8cYOY4EiW285VcQ52ZKztSLQ-PygWEIP6nZOPic0Hx86bSoPdOrs7gsKIwRbDiFJK_mwrPRr6ZnkkGoj9F_GVaVnNe6nK9uXa2iGrL5apVkKpQ6y-3VxP21bZMkQAWsA2yUWSxyJGirjFrs6SProE2kVBkiZXJe4akytU2AtqQwR0bjRDnrXN35dV0SYs8l85UK1f9G5CoQ4BQ2EIbEIZYphqhzh7nlvcjLp2I1qSWHneNsx3QX_RyJtk-DD3aeKwFIXGwLhH9D1soSdWAAdwJDNZcatpoHNoVvCNiZiqtkDaXUyH1Q
Content-Length: 0
Connection: close
Server: Jetty(9.2.22.v20170606)

HTTP/1.1 100 Continue

HTTP/1.1 201 Created
Date: Wed, 26 Jun 2019 20:59:29 GMT
Set-Cookie: JSESSIONID=1iky8xy4iegga1js55d155yme0;Path=/gateway/default;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/default; Max-Age=0; Expires=Tue, 25-Jun-2019 20:59:29 GMT
Location: https://104.42.55.227:30443/gateway/default/webhdfs/v1/partner_products/products.csv
Access-Control-Allow-Origin: *
Connection: close
Server: Jetty(9.2.22.v20170606)

.
Sample file uploads completed successfully.

**Comment by joelhulen** [comment]
I see what happened. I didn't have the latest version of the cmd file out there. Sorry about that.

Please re-run the curl command and then re-execute:

`curl -o upload-sample-files.cmd "https://raw.githubusercontent.com/solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019/master/Hands-on%20lab/Resources/upload-sample-files.cmd"`

**Comment by lifox1** [comment]
issue is resolved now with latest changes
