### ISSUE TITLE
exercise 5 task 3

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#18]
this query just clocks and will not complete.  Also instructions are not clear - are you supposed to change the compat level to 140 and run and then run at 150?

**Comment by joelhulen** [comment]
I just updated the instructions for clarity. It was set up just to observe what the result would be without the feature. I've updated to run the script once with a hint to disable the feature and observe, then again without the hint so you can observe with the feature enabled.

**Comment by lifox1** [comment]
ok great.  thanks

**Comment by joelhulen** [comment]
Closing, as this is addressed by latest changes.
