### ISSUE TITLE
excersice 5 task 4

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#19]
I get the disk spill on both queries

**Comment by joelhulen** [comment]
I'll clarify this one to run the second query a few times in a row. The spillage decreases each time until there are none. This happens as the statistics are updated with each run.

**Comment by lifox1** [comment]
ok I had to run it about 5 times

**Comment by joelhulen** [comment]
I updated the instructions to account for this, and have you observe the number of pages written each time you run it until there is no spillage.
