### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#20]
Overall, a good workshop.  The one piece that could probably be removed is the data masking.  This is not new to SQL 2019 so not sure what value it brings to the workshop.  Maybe something on  Always Encrypted with Secure Enclaves instead.

**Comment by joelhulen** [comment]
Thanks. Perhaps that's true about data masking. I'll leave that up to others to decide. As for Secure Enclaves, that's not supported by 2019 Big Data Clusters since you cannot install the hosted server components. Not sure what we'd demonstrate for Always Encrypted beyond how to configure it.
