### ISSUE TITLE
Location Layouts

### ISSUE THREAD

**Issue by BuckWoody** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#21]
Recommend you create a README.md in each directory. For instance, this page: https://github.com/solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Modernizing%20data%20analytics%20with%20SQL%20Server%202019.md could be renamed to that, since it contains the pre-reqs.

**Comment by joelhulen** [comment]
I totally agree, but this is the established layout and file names we've been told to use. Perhaps I could add a Readme file in that directory that points to the Before the HOL file.
