### ISSUE TITLE
Waiting for Controller Python Script failing

### ISSUE THREAD

**Issue by artfulbuster** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#22]
Hi 

I have tried to run the  python set up script,  python deploy-sql-big-data-aks.py  

I get the error saying the waiting for controller.
![errorControllerWaiting](https://user-images.githubusercontent.com/34212232/60361885-54b9ec80-99d7-11e9-94b9-f1605ae59fb6.jpg)

**Comment by joelhulen** [comment]
The screenshot is too small to read. Is this perhaps related to issue #6 ?

**Comment by artfulbuster** [comment]
Hi Joel

No its a different error. It is waiting for the pod controller to respond.



Sent from my Windows 10 device

**Comment by joelhulen** [comment]
What is your cluster instance name. This may also happen if the name is not truly unique.

**Comment by artfulbuster** [comment]
Hi Joel

Sorry had knocked off for the weekend , I have emailed SQL 2019 Team about it and waiting for a reply.

﻿ --
[Microsoft]
Craig Clayton
TECH SOLUTIONS PROF
Office: +44 (118) 9092787
Mobile: 07891879796
crclay@microsoft.com<mailto:crclay@microsoft.com>
9 AM - 6 PM

[Twitter]<https://twitter.com/Microsoft>    [Facebook] <https://www.facebook.com/Microsoft>     [Linkedin] <https://www.linkedin.com/company/microsoft>     [Youtube] <https://www.youtube.com/user/Microsoft>
﻿
This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG
