### ISSUE TITLE
Before the HOL - Task 1 - Step 10, 11, 12

### ISSUE THREAD

**Issue by thevinnie** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#23]
A few things from Before the HOL instructions

Task 2, Step 10
1. The step is requires the user to open a new window but it's very easy to miss.  Maybe move "Open a new Command Prompt window" to the beginning of line and bold it?
2. The first command begins with "REM" which effectively comments out the rest line.  REM should be removed.
3. When I did a clean installation of this section "C:\Python37\Scripts" and "C:\Python37" was already in the PATH, which I assumed happened in the previous Python install step.  Is the first command necessary?  If is is necessary, should you use %appdata% in the path so you don't need to have the user remember to put their username in the line?

Task 2, Step 11
4. Consider adding "Download and install" to the instruction.

Task 2, Step 12
5. Consider adding "Install the Azure Data Studio extension..."

**Comment by joelhulen** [comment]
Closing, as this is addressed by latest changes.
