### ISSUE TITLE
Before the HOL - Task 2 - Step 1

### ISSUE THREAD

**Issue by thevinnie** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#24]
In Task 2, Step 1:
"From your LabVM, download the starter files by downloading a .zip copy of the Cosmos DB real-time advanced analytics GitHub repo."

1. Since this could be from the users local machine or LabVM, maybe change that to not be specific to the LabVM?
2. This is referencing the wrong GitHub repo and should be updated.

**Comment by joelhulen** [comment]
Closing, as this is addressed by latest changes.
