### ISSUE TITLE
step 6 of pre req on Docker

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#5]
The Docker username provided to you as part of the limited public preview. - Where is this?  Need to be more clear on this - I just entered a random name and password.

**Comment by joelhulen** [comment]
Right now, you need to sign up for the EAP to receive a Docker username and password to install the preview pieces required for the lab. I did not add that in the lab in the hopes that by the time it is used it will be GA'd. Shoot me an email and I'll send you credentials you can use for now. joel@sollliance.net

**Comment by joelhulen** [comment]
Closing, as this is addressed by latest changes.
