### ISSUE TITLE
deployment script fails

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#6]
I get this error:
Deployment failed. Correlation ID: f6564b65-33ab-457c-ad38-72a42bcc8ba8. Service principal clientID: 19f6de75-5a1f-4bea-9df8-47f382b2db45 not found in Active Directory tenant 72f988bf-86f1-41af-91ab-2d7cd011db47, Please see https://aka.ms/aks-sp-help for more details.
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/fc4a4a29-ff9d-496f-9429-53ce27635745/resourceGroups/hands-on-lab-sql2019/providers/Microsoft.ContainerService/managedClusters/sql2019mcw/listClusterAdminCredential?api-version=2019-02-01 (Caused by ResponseError('too many 500 error responses',))

**Comment by joelhulen** [comment]
This may be related to you not having credentials to download the preview images of SQL 2019. Please see my comments on the other issue you opened (#5)

**Comment by joelhulen** [comment]
Closing, as this is addressed by latest changes.
