### ISSUE TITLE
upload sample files command

### ISSUE THREAD

**Issue by lifox1** [solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019#9]
Not 100% sure this was successful as I got this < was unexpected at this time so may be a problem with the code??  

C:\Users\lifox>.\upload-sample-files.cmd 104.42.55.227 MySQLBigData2019
< was unexpected at this time.

C:\Users\lifox><html><body>You are being <a href="https://raw.githubusercontent.com/solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019/master/Hands-onMySQLBigData20190lab/Resources/upload-sample-files.cmd">redirected</a>.</body></html>

**Comment by joelhulen** [comment]
I just fixed the curl command in the document.

Please delete that file and try downloading it again with this command:

`curl -o upload-sample-files.cmd "https://raw.githubusercontent.com/solliancenet/MCW-Modernizing-data-analytics-with-SQL-Server-2019/master/Hands-on%20lab/Resources/upload-sample-files.cmd"`
